### ISSUE TITLE
Issue reloading configuration

### ISSUE THREAD

**Issue by mdeweerd** [custom-components/climate.programmable_thermostat#44]
I get the following message in the log when reloading the configuration from the configuration submenu.

```
2021-11-17 18:35:58 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547627060816] Integration 'c' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 737, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/reload.py", line 169, in _reload_config
    await async_reload_integration_platforms(hass, domain, platforms)
  File "/usr/src/homeassistant/homeassistant/helpers/reload.py", line 49, in async_reload_integration_platforms
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/reload.py", line 59, in _resetup_platform
    integration = await async_get_integration(hass, integration_platform)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 594, in _async_get_integration
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration 'c' not found.
```

**Comment by MapoDan** [comment]
Ciao

yes, I know, but I don't know how to solve it..
Do you have any idea? if yes fell free to send a PR.

Daniele

**Comment by aladin2000** [comment]
I have the same issue during HASSio refresh stage in GUI of develop. 
Same from file_restore  but in that case, the letter is 'l' instead of 'c'

homeassistant.loader.IntegrationNotFound: Integration 'e' not found.

Any idea for z fix ?
For my case i use the 

**Home Assistant 2022.10.5 
Supervisor 2022.11.dev0802 
Interface utilisateur : 20221010.0 - latest**

**Comment by AnduriI** [comment]
I seem to have the same problem. I'm currently deploying that thermostat and whenever I try to only reload that part I get this error and have to restart HA as a whole.

**Comment by Aliskin-Papa** [comment]
My be remove this service from code? Because this bug stop Quick Restart ALL yaml configuration on the HA....

**Comment by litinoveweedle** [comment]
Hello having same issue with reloading. Was anyone able to solve the issue pointed by @mdeweerd ?

**Comment by gavoja** [comment]
The `async_setup_reload_service()` function takes a list as the third argument, not a string. See the method definition here: https://github.com/home-assistant/core/blob/2023.8.4/homeassistant/helpers/reload.py#L167

PR #67 fixes the issue.
